packaging_format = 2

id = "cowyo"
name = "Cowyo"
description.en = "Feature-rich wiki webserver for minimalists"
description.fr = "Serveur de wiki minimaliste mais riche en fonctionnalités"

version = "2.12.0~ynh5"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
demo = "https://cowyo.com"
admindoc = "https://github.com/schollz/cowyo/blob/master/README.md"
code = "https://github.com/schollz/cowyo"
website = "https://github.com/schollz/cowyo"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.0.9"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        amd64.url = "https://github.com/schollz/cowyo/releases/download/v2.12.0/cowyo_linux_amd64"
        amd64.sha256 = "C2F43C87FC3FF73A6A7D12D9DB7146C37375A94ECC5F37AE7B1F00B34782E241"
        armhf.url = "https://github.com/schollz/cowyo/releases/download/v2.12.0/cowyo_linux_arm"
        armhf.sha256 = "85A7BBFE930A636336BEE6EE3E5C44D43826AC0CE56FE462F77878C14F5BC440"
        i386.url = "https://github.com/schollz/cowyo/releases/download/v2.12.0/cowyo_linux_32bit"
        i386.sha256 = "CD29400F8E8D5B4551D8A6D244C3DF215072651984BE7D67E3619BC26135A13E"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
