packaging_format = 2

id = "cowyo"
name = "Cowyo"
description.en = "Feature-rich wiki webserver for minimalists"
description.fr = "Serveur de wiki minimaliste mais riche en fonctionnalités"

version = "2.12.0~ynh5"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
demo = "https://cowyo.com"
admindoc = "https://github.com/schollz/cowyo/blob/master/README.md"
code = "https://github.com/schollz/cowyo"
website = "https://github.com/schollz/cowyo"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        amd64.url = "https://github.com/schollz/cowyo/releases/download/v2.12.0/cowyo_linux_amd64"
        amd64.sha256 = "C2F43C87FC3FF73A6A7D12D9DB7146C37375A94ECC5F37AE7B1F00B34782E241"
        armhf.url = "https://github.com/schollz/cowyo/releases/download/v2.12.0/cowyo_linux_arm"
        armhf.sha256 = "85A7BBFE930A636336BEE6EE3E5C44D43826AC0CE56FE462F77878C14F5BC440"
        i386.url = "https://github.com/schollz/cowyo/releases/download/v2.12.0/cowyo_linux_32bit"
        i386.sha256 = "CD29400F8E8D5B4551D8A6D244C3DF215072651984BE7D67E3619BC26135A13E"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
