packaging_format = 2

id = "cowyo"
name = "Cowyo"
description.en = "Feature-rich wiki webserver for minimalists"
description.fr = "Serveur de wiki minimaliste mais riche en fonctionnalités"

version = "2.12.0~ynh5"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
demo = "https://cowyo.com"
admindoc = "https://github.com/schollz/cowyo/blob/master/README.md"
code = "https://github.com/schollz/cowyo"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        in_subdir = false
        extract = false
        rename = "cowyo"
        amd64.url = "https://github.com/schollz/cowyo/releases/download/v2.12.0/cowyo_linux_amd64"
        amd64.sha256 = "c2f43c87fc3ff73a6a7d12d9db7146c37375a94ecc5f37ae7b1f00b34782e241"
        armhf.url = "https://github.com/schollz/cowyo/releases/download/v2.12.0/cowyo_linux_arm"
        armhf.sha256 = "85a7bbfe930a636336bee6ee3e5c44d43826ac0ce56fe462f77878c14f5bc440"
        i386.url = "https://github.com/schollz/cowyo/releases/download/v2.12.0/cowyo_linux_32bit"
        i386.sha256 = "cd29400f8e8d5b4551d8a6d244c3df215072651984be7d67e3619bc26135a13e"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
